In [1]:
%pip install gensim

  Using cached scipy-1.13.1-cp310-cp310-win_amd64.whl.metadata (60 kB)
   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/24.0 MB 1.4 MB/s eta 0:00:18
   ---------------------------------------- 0.0/24.0 MB 1.4 MB/s eta 0:00:18
   ---------------------------------------- 0.0/24.0 MB 219.4 kB/s eta 0:01:50
   ---------------------------------------- 0.1/24.0 MB 656.4 kB/s eta 0:00:37
   ---------------------------------------- 0.2/24.0 MB 919.0 kB/s eta 0:00:26
   ---------------------------------------- 0.3/24.0 MB 1.0 MB/s eta 0:00:24
    --------------------------------------- 0.3/24.0 MB 1.1 MB/s eta 0:00:22
    --------------------------------------- 0.3/24.0 MB 1.1 MB/s eta 0:00:22
    --------------------------------------- 0.5/24.0 MB 1.2 MB/s eta 0:00:20
   - -------------------------------------- 0.7/24.0 MB 1.5 MB/s eta 0:00:16
   - --------

In [7]:
import gensim.downloader
model = gensim.downloader.load('glove-wiki-gigaword-100')
model["cat"] #查看'cat'单词的向量表示   

array([ 0.23088  ,  0.28283  ,  0.6318   , -0.59411  , -0.58599  ,
        0.63255  ,  0.24402  , -0.14108  ,  0.060815 , -0.7898   ,
       -0.29102  ,  0.14287  ,  0.72274  ,  0.20428  ,  0.1407   ,
        0.98757  ,  0.52533  ,  0.097456 ,  0.8822   ,  0.51221  ,
        0.40204  ,  0.21169  , -0.013109 , -0.71616  ,  0.55387  ,
        1.1452   , -0.88044  , -0.50216  , -0.22814  ,  0.023885 ,
        0.1072   ,  0.083739 ,  0.55015  ,  0.58479  ,  0.75816  ,
        0.45706  , -0.28001  ,  0.25225  ,  0.68965  , -0.60972  ,
        0.19578  ,  0.044209 , -0.31136  , -0.68826  , -0.22721  ,
        0.46185  , -0.77162  ,  0.10208  ,  0.55636  ,  0.067417 ,
       -0.57207  ,  0.23735  ,  0.4717   ,  0.82765  , -0.29263  ,
       -1.3422   , -0.099277 ,  0.28139  ,  0.41604  ,  0.10583  ,
        0.62203  ,  0.89496  , -0.23446  ,  0.51349  ,  0.99379  ,
        1.1846   , -0.16364  ,  0.20653  ,  0.73854  ,  0.24059  ,
       -0.96473  ,  0.13481  , -0.0072484,  0.33016  , -0.1236

In [8]:
model["cat"].shape

(100,)

In [3]:
model.most_similar("man")

[('woman', 0.8323495388031006),
 ('boy', 0.7914872169494629),
 ('one', 0.7788748145103455),
 ('person', 0.7526814937591553),
 ('another', 0.752223551273346),
 ('old', 0.7409116625785828),
 ('life', 0.7371699213981628),
 ('father', 0.7370322942733765),
 ('turned', 0.7347696423530579),
 ('who', 0.7345511317253113)]

In [4]:
 model.similarity("man", "woman")

0.8323492

In [5]:
model.similarity("king", "queen")

0.75076896

In [17]:
model.most_similar("king")

[('prince', 0.7682329416275024),
 ('queen', 0.7507691383361816),
 ('son', 0.7020889520645142),
 ('brother', 0.6985775828361511),
 ('monarch', 0.6977890133857727),
 ('throne', 0.6919989585876465),
 ('kingdom', 0.6811408400535583),
 ('father', 0.6802030205726624),
 ('emperor', 0.6712856888771057),
 ('ii', 0.6676074266433716)]

In [16]:
m = model["king"] - model["man"] + model["woman"]
model.most_similar(m)

[('king', 0.8551837801933289),
 ('queen', 0.7834415435791016),
 ('monarch', 0.6933802366256714),
 ('throne', 0.6833108067512512),
 ('daughter', 0.6809080839157104),
 ('prince', 0.6713144183158875),
 ('princess', 0.664408266544342),
 ('mother', 0.6579325795173645),
 ('elizabeth', 0.6563299894332886),
 ('father', 0.6392419338226318)]

In [9]:
m = model["father"] - model["man"] + model["woman"]
model.most_similar(m)

[('mother', 0.9137227535247803),
 ('daughter', 0.8749412894248962),
 ('father', 0.8659167289733887),
 ('wife', 0.8636060357093811),
 ('husband', 0.8385109901428223),
 ('grandmother', 0.8167359828948975),
 ('sister', 0.7944930791854858),
 ('woman', 0.7886242866516113),
 ('married', 0.7882134914398193),
 ('son', 0.7741048336029053)]

In [1]:
import numpy as np

Q = np.array([[4, 5, 6], 
              [1, 2, 3], 
              [7, 8, 9]])

K = np.array([[4, 5, 6], 
              [1, 2, 3], 
              [7, 8, 9]])

V = np.array([[4, 5, 6],
              [1, 2, 3],
              [7, 8, 9]])

np.dot(Q, K)

array([[ 63,  78,  93],
       [ 27,  33,  39],
       [ 99, 123, 147]])

In [2]:
from math import sqrt
dk = sqrt(K.shape[1]) #dk = sqrt(3)

l

In [4]:
# do softmax on Q dot K divided by sqrt(dk)
np.dot(softmax(np.dot(Q, K) / dk), V)


array([[3.76740938e-09, 4.71314634e-09, 5.65888330e-09],
       [3.53818655e-18, 4.42275353e-18, 5.30732051e-18],
       [1.20000000e+01, 1.50000000e+01, 1.80000000e+01]])

In [5]:
softmax(np.array([11.7, -2.6]))

array([9.99999384e-01, 6.16011247e-07])